### ISSUE TITLE
Como usar?

### ISSUE THREAD

**Issue by igorteuri** [arturcp/skoob-exporter#74]
Opa, beleza?

Sou leigo cara, mas queria usar o programa. Tentei instalar as dependências mas nem sei onde rodo esse comando. 
Tem algum lugar que ensina?

**Comment by arturcp** [comment]
Olá, @igorteuri, tudo bom?

Se sua idea é usar o exportador, o mais fácil é acessar o [site do exportador](https://skoob-exporter.colabs.dev/), mas acabei de ver que o certificado expirou. Vou corrigir isso.

Para executar o projeto localmente, você pode seguir as instruções que ficam no arquivo README.md, que está na raiz do projeto. Basicamente, você vai precisar ter instalado na sua máquina:

```
Ruby 3.1.2
Rails 6.1.3.1
Postgress 9.6.1
```

Você vai precisar configurar as variáveis de ambiente. Duplique o arquivo `.env.example` e renomeie para `.env`, e troque ao menos o valor do atributo `REDIS_URL` para `REDIS_URL=redis://localhost:6379`

Depois, execute esses dois comandos:
```
 bundle install
  bin/rake db:create db:migrate
```

Por fim, siga esses passos:

https://github.com/arturcp/skoob-exporter#how-to-run-it-locally

Se estiver dando algum erro me avise que vamos ajustando.

**Comment by igorteuri** [comment]
Ei @arturcp, muito obrigado pelo tutorial detalhado e suporte. Vou fazer o processo aqui.
Parabéns pelo trabalho!

**Comment by arturcp** [comment]
Muito obrigado, @igorteuri 💚
