### ISSUE TITLE
Exportar quadrinhos

### ISSUE THREAD

**Issue by leandroandrade87** [arturcp/skoob-exporter#77]
Olá, primeiramente parabéns pelo trabalho!
Eu utilizei o site para fazer a export dos meus livros do Skoob, mas percebi que o csn só veio com os dados dos Livros, mas também tenho vários quadrinhos cadastrados. 
Sabe se é possível adicionar essa funcionalidade também?
Eu até fiz algo utilizando Google Spreadsheet para poder gerar uns gráficos pra mim mesmo, mas alguns dados eu não consegui encontrar nas apis do Skoob, como por exemplo o dado de ISBN.

Muito Obrigado

**Comment by arturcp** [comment]
Olá, @leandroandrade87, tudo bom? Desculpe pela demora, levei quase dois meses para ver que tinha essa issue aberta. Eu nunca tinha usado a parte de quadrinhos do Skoob, vou dar uma olhada e ver o quão difícil é para incluir na exportação, obrigado por me avisar.

**Comment by leandroandrade87** [comment]
Tudo bom, @arturcp !
Sem problemas 👍 
Para adicionar um quadrinho você pode ir nessa parte:
<img width="957" alt="Screenshot 2023-07-08 at 14 35 03" src="https://github.com/arturcp/skoob-exporter/assets/2530875/f84add63-de4c-4de0-ab83-a1a4f8c7238f">

**Comment by arturcp** [comment]
@leandroandrade87 Fiz as alterações necessárias para exportar quadrinhos e revistas. Quando puder, você consegue testar o exportador?

**Comment by leandroandrade87** [comment]
Fui pelo site e mandei exportar os dados, demorou mais ou menos uns 15 minutos até ficar travado na seguinte tela:
<img width="918" alt="Screenshot 2023-07-14 at 21 24 31" src="https://github.com/arturcp/skoob-exporter/assets/2530875/33e9e15a-5f31-4282-9eb5-6d522257892f">

**Comment by arturcp** [comment]
@leandroandrade87 Eu instalei o SDK do Rollbar para que eu possa ver detalhes de erros quando eles acontecerem, e no processo de analisar onde mais eu poderia colocar logs eu encontrei um erro na hora de exibir os livros duplicados. Esse erro deve ter travado seu processo de importação. Você pode testar novamente?

**Comment by leandroandrade87** [comment]
Agora foi! 👍 
Só não foi preenchido os campos de date_read nem o rating.

**Comment by arturcp** [comment]
Quando eu criei o projeto eu não tinha acesso fácil a esses dados, mas depois o projeto foi mudando e nunca voltei para olhar esses dois campos novamente. Acabei de ajustar aqui e já deve estar exportando direitinho 👍 Muito obrigado pelos feedbacks!

**Comment by arturcp** [comment]
Agora que está tudo funcionando vou fechar essa issue, mas qualquer problema que encontrar fique à vontade para abrir uma nova issue 🙏

**Comment by leandroandrade87** [comment]
Tudo certo, parabéns pelo trabalho!
