### ISSUE TITLE
The site is only exporting reading not all books

### ISSUE THREAD

**Issue by Skywalker0204** [arturcp/skoob-exporter#82]
Is only exporting reading

**Comment by arturcp** [comment]
@Skywalker0204 I have been migrating the project to a new server, can you take a look if the error still persists? I have manage to export all my books right now. If the error still happens, can you provide more information? (You can write in Portuguese if you prefer)

**Comment by Skywalker0204** [comment]
Skoob Exporter - Google Chrome 2023-07-07 08-09...
<https://drive.google.com/file/d/1rTgdW8nB61SG-Cg__rLb_mf12L2OUT4Y/view?usp=drive_web>


Em seg., 3 de jul. de 2023 às 19:52, Artur Caliendo Prado <
***@***.***> escreveu:

**Comment by Skywalker0204** [comment]
é isso que acontece, fica tudo em branco, possível que seja algo com a
biblioteca pra fazer o csv

Em sex., 7 de jul. de 2023 às 08:15, Caio Mateus ***@***.***>
escreveu:

**Comment by arturcp** [comment]
@Skywalker0204 Subi uma série de alterações e melhorias no exportador, você pode tentar novamente? Agora no final da exportação você vai ver na tela os livros importados, não esqueça de clicar no botão "Baixar" do lado esquerdo quando ele aparecer para fazer o download do .csv.

**Comment by arturcp** [comment]
Outros usuários que estavam com problemas reportaram que agora tudo está funcionando. Vou fechar a issue, mas sinta-se à vontade para abrir uma nova caso encontre algum problema.
